$bridge_interface = `ip route | awk '/^default/ {printf $5}'`
NW = "192.168.7."
machines = {
  ctrlplane: "101",
  node: ["111", "112"]
}


Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.define "ctrlplane-#{machines[:ctrlplane]}" do |node|
    node.vm.provider :virtualbox do |vb|
      vb.name = "[k8s] Control Plane: #{machines[:ctrlplane]}"
    end
    machine_ip = NW + machines[:ctrlplane]
    node.vm.box = "debian/bookworm64"
    node.vm.network "public_network", bridge: "#$bridge_interface", ip: machine_ip
    node.vm.hostname = "ctrlplane-" + machines[:ctrlplane]

  end

  machines[:node].each do |item|

    config.vm.define "node-#{item}" do |node|
      node.vm.provider :virtualbox do |vb|
        vb.name = "[k8s] Node: #{item}"
      end

      machine_ip = NW + item
      node.vm.box = "debian/bookworm64"
      node.vm.network "public_network", bridge: "#$bridge_interface", ip: machine_ip
      node.vm.hostname = "node-" + item

      if item == machines[:node][-1]
        node.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible/k8s.yaml"
          ansible.limit = "all"
        end
      end

    end
  end

end
